### ISSUE TITLE
Update to 1.8.3

### ISSUE THREAD

**Issue by Wild1145** [DarthCraft/DarthCraft#101]
Not sure exactly how much damage 1.8.3 will be causing us, but im somewhat sure that there will be some bugs that we will need to fix.

**Comment by tylerhyperHD** [comment]
http://tcpr.ca/files/craftbukkit/craftbukkit-1.8.3-R0.1-SNAPSHOT-latest.jar

**Comment by Wild1145** [comment]
Thanks for the link however we will use our own jars hosted on the SN severs as we know they are not tampered with
