### ISSUE TITLE
Deprecated Code

### ISSUE THREAD

**Issue by tylerhyperHD** [DarthCraft/DarthCraft#107]
The following code is deprecated:
https://github.com/DarthCraft/DarthCraft/blob/master/src/net/darthcraft/dcmod/commands/Command_like.java
https://github.com/DarthCraft/DarthCraft/blob/master/src/net/darthcraft/dcmod/addons/AbductionHammer.java

Deprecation Source:
            for (Block block : player.getLineOfSight(null, 50))
and
            final Block block = ((Player) sender).getTargetBlock(null, 10);

**Comment by Wild1145** [comment]
I dont see the problem...
