### ISSUE TITLE
Re-Work XP Sharing

### ISSUE THREAD

**Issue by Wild1145** [DarthCraft/DarthCraft#110]
Just been informed that the current way we do XP sharing is just a tad OP. We need to do some serious Re-Work ASAP so you are sharing the actual XP, not the level XP.

**Comment by Wild1145** [comment]
By the looks of it, you can only add / remove levels, I've yet to see any other way of doing it. @WickedGamingUK @JeromSar any ideas?

**Comment by JeromSar** [comment]
@Wild1145 How about premium only, with a fixed maximum amount of XP per day?

For the XP calculation, there's a formula here: http://minecraft.gamepedia.com/Experience
There should be two API methods, if I'm correct: One for XP and one for XP-Levels. You should probably work with the XP one.

**Comment by Wild1145** [comment]
@JeromSar Premium only is one option, and the maximum XP is another, but thats not so much of the problem. The issue I had was only being able to find the XP Levels methood, I couldnt see anything for actual XP when I did some research, so the problem is people getting huge quantities of XP by just sharing all their XP and then leveling up a few levels and doing it again.

**Comment by JeromSar** [comment]
@Wild1145 There should be two API methods, I believe.

**Comment by Wild1145** [comment]
@JeromSar I will take a closer look and see if I just missed it, I guess I missed it when I was working on this the first time.
