### ISSUE TITLE
Premiums having a different colour chat.

### ISSUE THREAD

**Issue by Wild1145** [DarthCraft/DarthCraft#117]
I think its time we gave premiums something else to allow them to show off with! I would like to give them some cool in game chat color to brag to other players in :)

**Comment by muslimpotato** [comment]
Would be cool! We used to have purple letters i think. However Purple Tag + Purple letters would look bad. What about light blue letters?

**Comment by cresto630** [comment]
Well, it might be cool, but there are often a ton of premiums online and chat might get a little messy if the majority of chat has a color.
