### ISSUE TITLE
Remove GEOIP Support

### ISSUE THREAD

**Issue by Wild1145** [DarthCraft/DarthCraft#119]
Currently MaxMind is not doing what I want it to be doing, so I think it best to pull support for it.

**Comment by Wild1145** [comment]
This will not happen now with the 3.0 Re-Write.

**Comment by Scuph** [comment]
So you are re adding it?

@Wild1145

**Comment by Wild1145** [comment]
It may be re-added in the 3.0 or later releases, however is a low priority.
