### ISSUE TITLE
depend

### ISSUE THREAD

**Issue by TheRevalation** [DarthCraft/DarthCraft#134]
@Wild1145 I emailed you in january about maxmindgeoip in order for me to edit darthcraft to fit my server and not have the default setup, But I never got it and I seriously need it if I want my server to take off.

if you have it email it to me at hentscheljr1@aol.com

I really need it asap so if you can get it to me today, that would be nice.

**Comment by Wild1145** [comment]
@TheRevalation We have pulled the dependency from the server ourselves, so you could not need it anymore. Everything that uses it should simply be commented out in the DCMod Code if you're using the latest builds.
