### ISSUE TITLE
"Love" and "<3" no longer show in pink

### ISSUE THREAD

**Issue by oscarandjo** [DarthCraft/DarthCraft#147]
I'm not sure if this is a bug or intentional, but it was a highly important feature that was fundamental to the function of the server. Members on the server were outraged today that it wasn't showing pink as intended.

<3

- Oscar

**Comment by Wild1145** [comment]
It appears that the events are no longer firing... Something that is causing just about everything to break. I am unsure as to why they would have stopped working as nothing has changed for some time. Maybe @JeromSar has an idea as to what could be causing this...

**Comment by Wild1145** [comment]
Events not firing was caused by a broken YAML File. It all appears to be working now.
