### ISSUE TITLE
Improvements to voting system (announcements)

### ISSUE THREAD

**Issue by oscarandjo** [DarthCraft/DarthCraft#148]
There are a few points of improvement I feel could be made to the voting system, notably the messages in chat.

* A single vote can take up to 5 lines of chat due, here is an example:
    1. A Thank you goes to xxxxxxx who has just voted for the
    2. server on TopG.org
    3. xxxxx revieved 100D for voting
    4. xxxxx has voted and won nothing of value. They can
    5. have this dirt as a sign of condolance

This can repeat 8 times due to the amount of sites we have, it dominates chat and is spammy.

* Serverpact.com has its announcement in capitals "... just voted for the server on SERVERPACT.COM" perhaps this could be converted to lower case to avoid spammyness.

* The prize announced to the user when winning a cake says "diamond cake", I think the message has just been written wrong as only a cake has been won and not a diamond.

* Only the item prize of winning dirt is announced in chat to everyone, not diamond or cake. Perhaps only diamond should be announced as it is a rare and notable thing.

* When winning dirt, gravel is actually given.

* Although untested and unproven, some people have said sometimes the message doesn't come in chat for some of the votes but they still get the cash for them. I can't verify if this is the case though.

**Comment by Wild1145** [comment]
Okay, here goes :) 

- The amount of space it takes up is a tricky one to fix, I want all that information to be shown, so I've cleaned it up a little bit.

 - I have now forced it to show all server services in ALL lowercase. I may tweak that again in the future to make it "Sentence case" but eh. 

 - The "Diamond Cake" issue was a glitch. Its now just cake as thats all you should have gotten, that was me working on this system in college originally and being stupid.

 - Everything won should be announced in chat. I think thats fixed now.

 - That was originally designed as a bit of a funny insult by the admins, I guess nobody remembered that.

 - That is true, around 30% of cases should have gotten nothing other than money. I have now added a message to that.
