### ISSUE TITLE
Forcing hostname

### ISSUE THREAD

**Issue by zD12** [DarthCraft/DarthCraft#39]
Hi there,
According to the following thread, https://www.darthcraft.net/forums/showthread.php?tid=2605, users are allowed modifications as long {provided it doesn't allow for an unfair advantage}.   The following server, DarthCraft, only tolerate version Minecraft 1.8.1, this requires users to use an unstable version of Minecraft Forge that doesn't support the forwarding of the actual hostname (Force-IP/domain).   This directly results in using connecting via Minecraft 1.8.1 Forge to be directly kicked upon joining.    I'd highly suggest for a method of individual users disabling with, within game, without requiring any special permissions.   The following command would exempt them from joining via set domain/IP, and would allow users to join via Minecraft Forge.   I know this is a merely a request, but, it would allow for users to join via Forge and use modifications sure as Inv. Tweaks and others.

Thanks,
Cowgomooo12

**Comment by Wild1145** [comment]
So, just to make sure I understand this, the force hostname doesnt work properly when you are on a hacked client?

**Comment by WickedGamingUK** [comment]
This is a Forge problem, as you said. I don't see the point of allowing people to disable the force hostname as it'll cause confusion in the future if the IP were to change.

**Comment by Wild1145** [comment]
See above comment.
