### ISSUE TITLE
MySQL Bans crashed server

### ISSUE THREAD

**Issue by pbgben** [DarthCraft/DarthCraft#56]
Read logs bottom to top

29.01 20:22:48 [Server] INFO at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:526)
29.01 20:22:48 [Server] INFO at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:623)
29.01 20:22:48 [Server] INFO at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316)
29.01 20:22:48 [Server] INFO at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:683)
29.01 20:22:48 [Server] INFO at java.util.concurrent.FutureTask.run(Unknown Source)
29.01 20:22:48 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
29.01 20:22:48 [Server] INFO at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13)
29.01 20:22:48 [Server] INFO at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:53)
29.01 20:22:48 [Server] INFO at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:26)
29.01 20:22:48 [Server] INFO at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:940)
29.01 20:22:48 [Server] INFO at net.minecraft.server.v1_8_R1.PlayerConnection.handleCommand(PlayerConnection.java:1105)
29.01 20:22:48 [Server] INFO at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.java:642)
29.01 20:22:48 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181)
29.01 20:22:48 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
29.01 20:22:48 [Server] INFO at com.earth2me.essentials.Essentials.onCommand(Essentials.java:402)
29.01 20:22:48 [Server] INFO at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:417)
29.01 20:22:48 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
29.01 20:22:48 [Server] INFO at net.darthcraft.dcmod.DarthCraft.onCommand(DarthCraft.java:238)
29.01 20:22:48 [Server] INFO at net.darthcraft.dcmod.commands.Command_ban.run(Command_ban.java:85)
29.01 20:22:48 [Server] INFO at net.darthcraft.dcmod.DC_Utils.updateDatabase(DC_Utils.java:159)
29.01 20:22:48 [Server] INFO [20:22:48 ERROR]: [DarthCraft] java.lang.NullPointerException
29.01 20:22:48 [Server] INFO [20:22:48 ERROR]: [DarthCraft] Unknown command error: null
29.01 20:22:48 [Server] INFO [20:22:48 INFO]: wild1145 left the game.

**Comment by Wild1145** [comment]
Assumed to be fixed as I have not been told otherwise.
