### ISSUE TITLE
Incentive to re-plant trees and such.

### ISSUE THREAD

**Issue by Wild1145** [DarthCraft/DarthCraft#63]
Im thinking it would be good to have some sort of automated incentive for players to want to re-plant trees and such around the world, something we can code into DCMod to manage that would be even better.

**Comment by pbgben** [comment]
How about 1 xp per plant? it could just pop out the sapling. Maybe a random
chance of more than one.

On Mon, Feb 9, 2015 at 8:00 AM, Ryan <notifications@github.com> wrote:

> Im thinking it would be good to have some sort of automated incentive for
> players to want to re-plant trees and such around the world, something we
> can code into DCMod to manage that would be even better.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/DarthCraft/DarthCraft/issues/63>.
>



-- 
Ben Carrington
[pbgben]

**Comment by Wild1145** [comment]
@pbgben That could work quite well, the only issue may be players abusing it... Thats the only thing we will need to find a work around for...

**Comment by pbgben** [comment]
Ahh, yes.... They could just place and pickup... how about we also
introduce a negative to removing saplings :P like -1xp per removal

On Mon, Feb 9, 2015 at 9:22 AM, Ryan <notifications@github.com> wrote:

> @pbgben <https://github.com/pbgben> That could work quite well, the only
> issue may be players abusing it... Thats the only thing we will need to
> find a work around for...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/DarthCraft/DarthCraft/issues/63#issuecomment-73429516>
> .
>



-- 
Ben Carrington
[pbgben]

**Comment by Wild1145** [comment]
I was thinking -4 or something, that way its like an "evil" to remove saplings.

**Comment by pbgben** [comment]
Yeh, you could enven create a counter or something that shows a message
when a payer removes too many, like 10 or something. "$player hates trees,
make them feel bad!"


On Mon, Feb 9, 2015 at 10:34 AM, Ryan <notifications@github.com> wrote:

> I was thinking -4 or something, that way its like an "evil" to remove
> saplings.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/DarthCraft/DarthCraft/issues/63#issuecomment-73433268>
> .
>



-- 
Ben Carrington
[pbgben]

**Comment by Wild1145** [comment]
That could be quite amusing. Its definitely something I will try to add!

**Comment by muslimpotato** [comment]
Removing trees costing xp does not sound too good to me. It gives me the impression you will be forced to pay for trees. Punching trees is one of the key elements of starting a life in a survival based server. To make it cost xp will in my eyes take this survival based element away. Replanting trees on the other hand should be awarded. Because if a player destroys a tree, they will instantly regrow the trees to receive xp.

**Comment by Wild1145** [comment]
@muslimpotato Its not removing the tree, but breaking a sapling. This way you dont just place them and remove them and place them to earn loads of free XP.
