### ISSUE TITLE
Improper English

### ISSUE THREAD

**Issue by zD12** [DarthCraft/DarthCraft#71]
Certain messages aren't using proper English, and to be frank, it's kinda annoying.
![2015-02-18_17 32 29](https://cloud.githubusercontent.com/assets/7622961/6258151/31e344ba-b794-11e4-8f35-750379bba79b.png)

It's not showing how truly awesome the server actual issue.  It looks unprofessional.

**Comment by Wild1145** [comment]
Links with #57 quite a lot.

**Comment by Wild1145** [comment]
Resolved in earlier commit.
