### ISSUE TITLE
set login permissions

### ISSUE THREAD

**Issue by xDestroyer217** [DarthCraft/DarthCraft#79]
* 'setlogin' is being allowed for normal Members (ex. me)
* 'dellogin' as well
* When I do setlogin, it does set the login message, but it doesn't show up

* Good thing tiff did not kill me :3

**Comment by Wild1145** [comment]
Thats intentional. The idea is that you can save a login message, so if we want to enable it for a special event for all players you have messages. It also means if you upgrade to premium, you will instantly have the message available to you.
