### ISSUE TITLE
This might be right

### ISSUE THREAD

**Issue by theLAZYway01** [DarthCraft/DarthCraft#80]
Wild, This is the only place you have responded to me quickly. Two things

Im now a certified java developer by the school that taught me and I would like to talk about maybe joining the dev team, and I sent an email for the MaxmindGeoIP jar file, please review it. For more about joining the dev team either PM me on TF for my skype or other ways of contact, also a few things:

Stfu desc says mutes with more force, but the bcast and when they talk is the same

The warn bcast message is also messed up,

With MySQL disabled, the console still gets errors when a ban occurs

If I join the team, I could fix these without a problem

Thanks!
DaPancake

**Comment by Wild1145** [comment]
When it comes to developer rank, this is what you need to take a look at: https://www.darthcraft.net/forums/showthread.php?tid=2369

As for the issues, if you fix them, PR them and if its good quality, I can consider you taking a developer rank. As for the dependency, if you e-mailed me, I will be getting to them shortly, I have just been a tad busy.

**Comment by theLAZYway01** [comment]
Applied. I'd rather fix the original source. Closed
