### ISSUE TITLE
Forge dun goofing

### ISSUE THREAD

**Issue by Wild1145** [DarthCraft/DarthCraft#87]
[01:37:18] [Server thread/INFO]: [TotalFreedomMod] Hostname: play.totalfreedom.meFML:28965]

Forge Mod Loader appends FML to the hostname in the log, which is what prevents a player using at least certain versions FML from joining TotalFreedom. I dont get how they are even managing to establish a connection though with the suffix. I would think that it would fail to resolve the domain with meFML.

Anyways, this is why some FML users are getting kicked for not joining with the correct IP/domain.

**Comment by WickedGamingUK** [comment]
This issue isn't resolved. You still get kicked asking you to join on the hostname.

**Comment by Wild1145** [comment]
There is a problem with the new code as it does not allow any connections for some reason.
