### ISSUE TITLE
Online Dynamic Map

### ISSUE THREAD

**Issue by oscarandjo** [DarthCraft/DarthCraft#89]
A while back when looking for a biome that I had previously passed but couldn't find, I remembered that Tektoncraft (predecessor to Darthcraft) had a dynamic online map of the world. I as well as many others used this regularly and I believe it was updated nightly when not many people were on.

I would love to see a dynamic map return to DarthCraft!

Some things to consider would be the extra CPU load and bandwidth utilisation this could cause, however I believe CPU usage is low when not refreshing the map and Crafting.tk servers have enough bandwidth. I previously discussed this with Ben and he didn't seem to have any hesitations.

**Comment by Wild1145** [comment]
Something to post on the forums, as this wont be implemented into DCMod its self, because I dont have a death wish :P ;)
