### ISSUE TITLE
This really isn't an issue, but help is needed and will be rewarded if fixed

### ISSUE THREAD

**Issue by DaPancake** [DarthCraft/DarthCraft#91]
I have a plugin (shadoweracore) and I have a command /promote that replaces /manuadd and if you promote player it promotes them and sends out a public congratulations message much like your /setrank, but when I execute the command

I keep getting

(&c red chat) 'Command  promote not loaded!'

Thus I need someone who can help me with this and fix the problem!

If you do, you will be heavily rewarded.

**Comment by theLAZYway01** [comment]
here is the coding:

http://pastebin.com/KLtmQAMs

**Comment by Wild1145** [comment]
Its quite probable that you did not add the command to the plugin.yml as thats what normally shows when you forget that.

**Comment by DaPancake** [comment]
Fixed, it took a while

Closed.
