### ISSUE TITLE
Vote To Play

### ISSUE THREAD

**Issue by Wild1145** [DarthCraft/DarthCraft#92]
Ben has suggested that we make it so for every vote you place, you get a days access to the server. This should be reasonable alright to implement, just going to require a bit of work and thinking through!

**Comment by JeromSar** [comment]
:C

**Comment by Wild1145** [comment]
@JeromSar Is that a not approval of the idea or how I implemented it?

**Comment by WickedGamingUK** [comment]
@Wild1145 From speaking to him at the time he knew about it, the idea.

**Comment by Wild1145** [comment]
@WickedGamingUK Fair enough. 

I should point out, its a configurable option. So if we decide we dont like it, its easy enough to just disable and reload.
