### ISSUE TITLE
Server List Ping Bug

### ISSUE THREAD

**Issue by WickedGamingUK** [DarthCraft/DarthCraft#97]
This is probably done through a separate plugin, however when you ping the server and no one is online you can get this message:

![https://www.screenshottr.us/v/07ff94e65320e0db66c4ba4f04abac9d/60d6a5a6a45fb26a8b726c3f292083b2.png](https://www.screenshottr.us/v/07ff94e65320e0db66c4ba4f04abac9d/60d6a5a6a45fb26a8b726c3f292083b2.png)

**Comment by Wild1145** [comment]
This is handled through a separate plugin and is a fault with their plugin. Not something we can really fix...
